# reference: https://github.com/mlibrary/heliotrope/blob/master/.rubocop_todo.yml
# Put any overides here
#Lint/AmbiguousBlockAssociation:
#  Exclude:
#    - 'spec/controllers/hyrax/monographs_controller_spec.rb'
#    - 'spec/controllers/roles_controller_spec.rb'

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LeadingCommentSpace:
  Exclude:
    - 'config/initializers/mailboxer.rb'

Layout/SpaceInsideBrackets:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceAroundOperators:
  Exclude:
    - config/application.rb

Lint/RescueException:
  Exclude:
    - 'lib/append_content_service.rb'
    - 'lib/build_content_service.rb'

Metrics/BlockLength:
  Enabled: true
  Max: 295 # default is 25

#Metrics/ClassLength:
#  Exclude:
#    - 'app/controllers/catalog_controller.rb'
#    - 'app/presenters/hyrax/file_set_presenter.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/hyrax/data_sets_controller.rb'
    - 'app/helpers/ingest_helper.rb'
    - 'app/helpers/metadata_helper.rb'
    - 'lib/tasks/new_content_service.rb'

Metrics/ModuleLength:
  Enabled: true
  Max: 1000 # default is 100

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/hyrax/data_sets_controller.rb'
    - 'app/helpers/ingest_helper.rb'
    - 'app/helpers/metadata_helper.rb'
    - 'lib/tasks/new_content_service.rb'

Rails/Exit:
  Exclude:
    - 'lib/**/*'

#Rails/OutputSafety:
#  Exclude:
#    - 'spec/presenters/concerns/title_presenter_spec.rb'
#    - 'config/initializers/explain_partials.rb'
#    - 'app/services/markdown_service.rb'
#    - 'app/helpers/markdown_helper.rb'
#    - 'app/helpers/gallery_helper.rb'
#    - 'app/renderers/hyrax/renderers/attribute_renderer.rb'
#    - 'app/renderers/hyrax/renderers/markdown_attribute_renderer.rb'

#Rails/SkipsModelValidations:
#  Exclude:
#    - 'spec/jobs/characterize_job_spec.rb'

#RSpec/EmptyExampleGroup:
#  Exclude:
#    - 'spec/actors/hyrax/monograph_actor_spec.rb'

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: true
  Max: 103 # default is 5

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

#RSpec/SubjectStub:
#  Exclude:
#    - 'spec/models/riiif/file_spec.rb'

RSpec/VerifiedDoubles:
  Enabled: false

#Style/ClassVars:
#  Exclude:
#    - app/helpers/metadata_helper.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/initializers/mailboxer.rb'

#Style/GuardClause:
#  Exclude:
#    - 'lib/import/importer.rb'

Style/NumericLiterals:
  Exclude:
    - 'config/initializers/mailboxer.rb'

Style/RedundantReturn:
  Enabled: false

#Style/VariableName:
#  Exclude:
#    - app/helpers/metadata_helper.rb

Style/YodaCondition:
  Enabled: false
