terms:
    - id: Centers for Disease Control and Prevention (CDC)
      term: Centers for Disease Control and Prevention (CDC)
    - id: Department of Defense (DOD)
      term: Department of Defense (DOD)
    - id: Department of Energy (DOE)
      term: Department of Energy (DOE)
    - id: Department of Transportation (DOT)
      term: Department of Transportation (DOT)
    - id: National Aeronautics and Space Administration (NASA)
      term: National Aeronautics and Space Administration (NASA)
    - id: National Endowment for the Humanities (NEH)
      term: National Endowment for the Humanities (NEH)
    - id: National Institutes of Health (NIH)
      term: National Institutes of Health (NIH)
    - id: National Science Foundation (NSF)
      term: National Science Foundation (NSF)
    - id: Other Funding Agency 
      term: Other Funding Agency
      