# config/scheduler_jobs_prod.yml

deactivate_embargoes_job:
  # Run once a day, five minutes after midnight
  #      M H
  cron: '5 0 * * *'
  # rails_env: production
  class: DeactivateEmbargoesJob
  queue: scheduler
  description: Deactivate embargoes job.
  args:
    email_owner: true
    test_mode: false
    verbose: true

about_to_deactivate_embargoes_job:
  # Run once a day, fifteen minutes after midnight
  #      M  H
  cron: '15 0 * * *'
  # rails_env: production
  class: AboutToExpireEmbargoesJob
  queue: scheduler
  description: About to deactivate embargoes job.
  args:
    email_owner: true
    test_mode: false
    verbose: true
