# config/scheduler_jobs_test.yml

#five_minute_heartbeat_job:
#  every:
#      - "5m"
#      - :first_in: '2s'
#  # cron: '0 12 * * *'
#  # rails_env: production
#  class: HeartbeatJob
#  queue: scheduler
#  args:
#  description: A job that runs every five minutes to write a heartbeat event the scheduler log.

five_minute_heartbeat_job:
  #      M   H
  cron: '*/5 * * * *'
  # rails_env: production
  class: HeartbeatJob
  queue: scheduler
  args:
  description: Write a heartbeat to the scheduler log on the five minute mark.

test_about_to_deactivate_embargoes_job:
  #      M  H
  cron: '*/5 * * * *'
  # rails_env: production
  class: AboutToExpireEmbargoesJob
  queue: scheduler
  description: Test about to deactivate embargoes.
  args:
    test_mode: true
    verbose: true
