# config/scheduler_jobs_prod.yml

deactivate_embargoes_job:
  # Run once a day, five minutes after midnight
  #      M H
  cron: '5 0 * * *'
  # rails_env: production
  class: DeactivateEmbargoesJob
  queue: scheduler
  description: Deactivate embargoes job.
  args:
    test_mode: true

about_to_deactivate_embargoes_job:
  # Run once a day, fifteen minutes after midnight
  #      M  H
  cron: '15 0 * * *'
  # rails_env: production
  class: AboutToExpireEmbargoesJob
  queue: scheduler
  description: About to deactivate embargoes job.
  args:
    test_mode: true

test_about_to_deactivate_embargoes_job:
  # Run once a day, fifteen minutes after midnight
  #      M  H
  cron: '*/10 * * * *'
  # rails_env: production
  class: AboutToExpireEmbargoesJob
  queue: scheduler
  description: Test about to deactivate embargoes (running every 10 minutes).
  args:
    test_mode: true
    verbose: true

test_deactivate_embargoes_job:
  # Run once a day, five minutes after midnight
  #      M H
  cron: '*/15 * * * *'
  # rails_env: production
  class: DeactivateEmbargoesJob
  queue: scheduler
  description: Test deactivate embargoes job (running every 15 minutes).
  args:
    test_mode: true
    verbose: true

