# config/scheduler_jobs_prod.yml

heartbeat_email_job:
  # Run once a day, one minute after midnight (which is offset by 4, due to GMT)
  #      M H
  cron: '1 4 * * *'
  # rails_env: production
  class: HeartbeatEmailJob
  queue: scheduler
  description: Heartbeat email job.
  args:
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'staging.deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'

deactivate_expired_embargoes_job:
  # Run once a day, five minutes after midnight (which is offset by 4, due to GMT)
  #      M H
  cron: '5 4 * * *'
  # rails_env: production
  class: DeactivateExpiredEmbargoesJob
  queue: scheduler
  description: Deactivate embargoes job.
  args:
    email_owner: true
    test_mode: false
    verbose: true

about_to_deactivate_embargoes_job:
  # Run once a day, fifteen minutes after midnight (which is offset by 4, due to GMT)
  #      M  H
  cron: '15 4 * * *'
  # rails_env: production
  class: AboutToExpireEmbargoesJob
  queue: scheduler
  description: About to deactivate embargoes job.
  args:
    email_owner: true
    test_mode: false
    verbose: true

user_stat_importer_job:
  # Run once a day, thirty minutes after midnight (which is offset by 4, due to GMT)
  #      M  H
  cron: '30 4 * * *'
  # rails_env: production
  class: UserStatImporterJob
  queue: scheduler
  description: Import user stats job.
  args:
    test: true
    hostnames:
      - 'deepblue.lib.umich.edu'
      - 'testing.deepblue.lib.umich.edu'
    logging: true
    verbose: true

#about_to_deactivate_embargoes_at_2_days_job:
#  # Run once a day, twenty minutes after midnight (which is offset by 4, due to GMT)
#  #      M  H
#  cron: '20 4 * * *'
#  # rails_env: production
#  class: AboutToExpireEmbargoesJob
#  queue: scheduler
#  description: About to deactivate embargoes job.
#  args:
#    email_owner: true
#    expiration_lead_days: 2
#    test_mode: false
#    verbose: true
