# Production environment configuration. These should generally receive values
# in settings.local.yml for deployed instances. If running a multi-environment
# instance for testing or debugging, production.local.yml may be helpful. As-is,
# they are compatible with a typical container-style approach, where default
# ports on generic hostnames are used for each service/resource.

hostname: 'deepblue.lib.umich.edu'

hyrax:
  redis_namespace: 'deepbluedata-production'

fedora:
  url: http://fcrepo/fedora/rest
  base_path: /deepbluedata-production

solr:
  url: http://solr/solr/deepbluedata-production

redis:
  url: redis://redis/

# Datacite client configuration
# Set real values in settings.production.local.yml or local environment file.
ezid:
  host: api.datacite.org
  username: datacite.production.user
  password: datacite.production.password
  prefix: invalid

jira:
  username: jirausername.invalid
  password: jirapassword.invalid
  site_url: https://tools.lib.umich.edu

rails:
  database:
    database: db/production.sqlite3
  # Set the key base in settings.local.yml or production.local.yml or use the
  # SECRET_KEY_BASE environment variable, which will take precedence. It is
  # left nil here to trigger the error message from Rails if not specified.
  secret_key_base:
  cable:
    adapter: redis
    url: redis://redis/
    channel_prefix: deepbluedata-production

omniauth:
  host: idp.login.iu.edu
